# Generated by Django 4.0.8 on 2022-11-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_by_receiver',
            field=models.BooleanField(default=False, help_text='Was the message deleted by the receiver?'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_sender',
            field=models.BooleanField(default=False, help_text='Was the message deleted by the sender?'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Was the message read by the receiver?'),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the message was sent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=models.CharField(help_text='The content of the message', max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(help_text='The subject of the message.', max_length=100),
        ),
    ]
