# Generated by Django 4.0.8 on 2022-11-30 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.CharField(help_text='The receiver of message.', max_length=100)),
                ('subject', models.CharField(help_text='The subject of the message.', max_length=100)),
                ('message_content', models.CharField(help_text='The content of the message', max_length=1000)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='The date and time the message was sent')),
                ('is_read', models.BooleanField(default=False, help_text='Was the message read by the receiver?')),
                ('sender', models.ForeignKey(help_text='Sender of the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
