# Generated by Django 4.0.8 on 2022-12-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(help_text='Sender of the message', max_length=100),
        ),
    ]
