# Generated by Django 4.0.8 on 2022-11-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_deleted_by_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deleted_by_receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted_by_sender',
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.CharField(help_text='The receiver of message.', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(help_text='The sender of the message.', max_length=100),
        ),
    ]
